# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Install any needed packages specified in requirements.txt
RUN pip install tweepy

# Set the working directory in the container
WORKDIR /workdir