name: Weekly Hourly Run

on:
  schedule:
    - cron: '0 * * * *'
    # - cron: '0 10-19 * * 1-5' # Runs every hour from 10 AM to 7 PM on weekdays
    # - cron: '0 20 * * 1-5'    # Runs at 8 PM on weekdays
  push:
    branches:
      - master

jobs:
  commit-date-time:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'test:') || github.event_name == 'schedule'


    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run update test
      run: |
        echo "This runs every hour in working days from 10-20h"
        # Generate new input hourly 
        docker run -w /wordir -v ${{ github.workspace }}:/workdir diegomscoelho/quarto_geo Rscript /workdir/scripts/get_missao.R
        # Generate plot to figs
        docker run -w /wordir -v ${{ github.workspace }}:/workdir diegomscoelho/quarto_geo Rscript scripts/missao_plot.R
        # Generate update to dash
        docker run -w /wordir -v ${{ github.workspace }}:/workdir diegomscoelho/quarto_geo quarto render index.qmd

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Get Current Date and Time
      id: current_datetime
      run: echo "datetime=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

    - name: Make a commit
      run: |
        git add .
        git commit -m "Autocommit on ${{ env.datetime }}"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
