name: Weekly Hourly Run

on:
  schedule:
    # - cron: '0 * * * *'
    - cron: '0 10-19 * * 1-5' # Runs every hour from 10 AM to 7 PM on weekdays
    - cron: '0 20 * * 1-5'    # Runs at 8 PM on weekdays
  push:
    branches:
      - main

jobs:
  commit-date-time:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'test:') || github.event_name == 'schedule'


    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global pull.rebase true  # Set the default pull strategy to rebase

    - name: Get Current Date and Time in America/Sao_Paulo
      id: current_datetime
      run: |
        sudo ln -snf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
        sudo dpkg-reconfigure -f noninteractive tzdata
        echo "datetime=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

    - name: Run update test
      run: |
        echo "This runs every hour in working days from 10-20h"
        # Generate new input hourly
        echo "datetime=$(date +'%Y-%m-%d %H:%M')" >> teste.txt
        # docker run -w /wordir -v ${{ github.workspace }}:/workdir diegomscoelho/quarto_geo Rscript scripts/get_missao.R
        # # Generate plot to figs
        # docker run -w /wordir -v ${{ github.workspace }}:/workdir diegomscoelho/quarto_geo Rscript scripts/missao_plot.R
        # # Generate update to dash
        # docker run -w /wordir -v ${{ github.workspace }}:/workdir diegomscoelho/quarto_geo quarto render index.qmd

    - name: Pull Latest Changes
      run: |
        git pull origin main

    - name: Make a commit
      run: |
        git add .
        git commit -m "Autocommit on ${{ env.datetime }}"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
