name: Weekly Hourly Run

on:
  schedule:
    - cron: '0 * * * *'
    # - cron: '0 10-19 * * 1-5' # Runs every hour from 10 AM to 7 PM on weekdays
    # - cron: '0 20 * * 1-5'    # Runs at 8 PM on weekdays

jobs:
  run-every-hour:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run update test
      run: echo "This runs every hour"
        # docker run -w /wordir -v ${{ github.workspace }}:/workdir diegomscoelho/quarto_geo Rscript /workspace/scripts/get_missao.R